services:
  postgresDb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "FitnessTrackerDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pk1Gwb98"
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  fitness-tracker-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: fitness-tracker-api
    depends_on:
      - postgresDb

volumes:
  postgres-data:
